// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovelSiteParser;

namespace NovelSiteParser.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20190703055707_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("NovelSiteParser.BookLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("IndexPage");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("BookLinks");
                });

            modelBuilder.Entity("NovelSiteParser.ChapterLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<bool>("Downloaded");

                    b.Property<int>("IndexNumber");

                    b.Property<long?>("IssueLinkId");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("IssueLinkId");

                    b.ToTable("ChapterLinks");
                });

            modelBuilder.Entity("NovelSiteParser.IssueLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("BookLinkId");

                    b.Property<int>("IndexNumber");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("BookLinkId");

                    b.ToTable("IssueLinks");
                });

            modelBuilder.Entity("NovelSiteParser.ChapterLink", b =>
                {
                    b.HasOne("NovelSiteParser.IssueLink")
                        .WithMany("ChapterLinks")
                        .HasForeignKey("IssueLinkId");
                });

            modelBuilder.Entity("NovelSiteParser.IssueLink", b =>
                {
                    b.HasOne("NovelSiteParser.BookLink")
                        .WithMany("IssueLinks")
                        .HasForeignKey("BookLinkId");
                });
#pragma warning restore 612, 618
        }
    }
}
